//! Pre-port Rust implementation of `sequence_parallel_copies`, kept verbatim
//! as a differential-testing reference. This is the impl that lived at
//! commit `1492076` before the Lean port (#120).
//!
//! It is **only** compiled under `cfg(test)` and is not used anywhere in
//! the production code path. Its purpose is so that tests can run the same
//! input through both the verified Lean-backed entry point and this original
//! Rust impl and compare results — both for regression checks against the
//! existing 47-test suite and for property-based search using the Lean spec
//! as oracle.
//!
//! Do not edit this file to fix bugs. If a divergence is found, document it
//! and either fix the underlying issue or add a regression test pinning the
//! observed behaviour.

#![allow(dead_code)]

use std::collections::{BTreeMap, btree_map::Entry};

use super::sequence_parallel_copies::Register;

/// Pre-port `sequence_parallel_copies`. See the module-level doc for context.
pub fn sequence_parallel_copies_legacy(
    parallel_copies: impl IntoIterator<Item = (u32, u32)>,
) -> impl Iterator<Item = (Register, Register)> {
    let mut graph: BTreeMap<u32, RegConnections> = BTreeMap::new();

    for (src, dst) in parallel_copies {
        if src == dst {
            continue;
        }
        let dst_entry = graph.entry(dst).or_default();
        if dst_entry.src == Some(src) {
            continue;
        }
        if dst_entry.src.is_some() {
            panic!(
                "Pre-condition violated: destination register {} is written to more than once",
                dst
            );
        }
        dst_entry.src = Some(src);
        graph.entry(src).or_default().dest.push(dst);
    }

    sequence_parallel_copies_impl(graph)
}

#[derive(Default)]
struct RegConnections {
    src: Option<u32>,
    dest: Vec<u32>,
}

fn sequence_parallel_copies_impl(
    mut graph: BTreeMap<u32, RegConnections>,
) -> impl Iterator<Item = (Register, Register)> {
    let mut tree_ends: Vec<u32> = graph
        .iter()
        .filter_map(|(&reg, conn)| conn.dest.is_empty().then_some(reg))
        .collect();

    let mut non_cycle_copies: Vec<(u32, u32)> = Vec::new();

    while let Some(target) = tree_ends.pop() {
        let source = graph[&target].src.unwrap();
        non_cycle_copies.push((source, target));

        let Entry::Occupied(mut source_entry) = graph.entry(source) else {
            panic!("Invariant violated: source register not found in graph");
        };
        let source_node = source_entry.get_mut();

        source_node.dest.retain(|&dst| dst != target);
        let remaining_dests = std::mem::take(&mut source_node.dest);

        if source_node.src.is_none() {
            source_entry.remove_entry();
        } else {
            tree_ends.push(source);
        }

        if remaining_dests.is_empty() {
            graph.remove(&target);
        } else {
            for &d in &remaining_dests {
                graph.get_mut(&d).unwrap().src = Some(target);
            }
            let target_entry = graph.get_mut(&target).unwrap();
            target_entry.src = None;
            target_entry.dest = remaining_dests;
        }
    }

    let tmp_register = non_cycle_copies
        .first()
        .map(|&(_, dst)| Register::Given(dst))
        .unwrap_or(Register::Temp);

    let mut cycle_copies: Vec<(Register, Register)> = Vec::new();
    while let Some(initial) = graph.keys().next().cloned() {
        cycle_copies.push((Register::Given(initial), tmp_register));

        let mut curr = initial;
        loop {
            let Entry::Occupied(curr_entry) = graph.entry(curr) else {
                panic!("Invariant violated: current register not found in graph");
            };
            let curr_node = curr_entry.get();
            assert_eq!(
                curr_node.dest.len(),
                1,
                "Invariant violated: cycle node has more than one destination"
            );

            let src = curr_node.src.unwrap();
            curr_entry.remove_entry();

            if src == initial {
                break;
            }

            cycle_copies.push((Register::Given(src), Register::Given(curr)));
            curr = src;
        }

        cycle_copies.push((tmp_register, Register::Given(curr)));
    }

    cycle_copies.into_iter().chain(
        non_cycle_copies
            .into_iter()
            .map(|(src, dst)| (Register::Given(src), Register::Given(dst))),
    )
}
